# NumPy 
* NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science.
* Numpy stands for Numerical python which is used to perform numerical calculations.
* Numpy is used to handle arrays and matrices.

# What is Numpy?
* Numpy in python is a library /package that used to work with arrays
* It is also a datastructure used to store multiple values.
* Numpy provides efficient way of storing and manipulating data.
* It offers wide variety of mathematical functions which helps in solving complex math problems of linear algebra,fourier transform and vectors.

# Why numpy?
- Faster and more compact than lists.
- consumes less memory
- data type can be specified
- high level mathematical functions can be used
- used to solve problems related to linear algebra, fourier transform ,vectors etc

# What is an array?
Numpy arrays commonly used data structures in python that store data as a grid, or a matrix and easy to access.

In [2]:
# import numpy package
import numpy as np

In [6]:
# create empty array
arr=np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


In [7]:
# create numpy array to store values such as 6,7,8,9,4,5,6
arr1=np.array([6,7,8,9,4,5,6])
print(arr1)
print(type(arr1))

[6 7 8 9 4 5 6]
<class 'numpy.ndarray'>


In [8]:
# create numpy array to store values such blue,green,orange,yellow,white
colors=np.array(("blue","green","orange","yellow","white"))
print(colors)
print(type(colors))

['blue' 'green' 'orange' 'yellow' 'white']
<class 'numpy.ndarray'>


In [9]:
# how to create an array using list
List=[34,56,78,98,76,56,45,34,23]
arr=np.array(List)
print(arr)
print(type(arr))

[34 56 78 98 76 56 45 34 23]
<class 'numpy.ndarray'>


In [10]:
# How to create array using tuple
tuple=(101,102,103,104,105,106,107,108)
arr=np.array(tuple)
print(arr)
print(type(arr))

[101 102 103 104 105 106 107 108]
<class 'numpy.ndarray'>


# 1-D array

In [15]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print("dimension of array is",arr.ndim)
print("number of elements is",arr.size)
print("data type of an array elements",arr.dtype)

[1 2 3 4 5 6]
dimension of array is 1
number of elements is 6
data type of an array elements int32


In [16]:
# 2-D array---- matrices
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
arr=np.array([[4,5,6,7],[8,9,1,2],[3,2,4,3],[9,2,1,4]])
print(arr)
print("dimension",arr.ndim)
print("no of elements",arr.size)
print("order of matrix",arr.shape)

[[4 5 6 7]
 [8 9 1 2]
 [3 2 4 3]
 [9 2 1 4]]
dimension 2
no of elements 16
order of matrix (4, 4)


# 3-D array

In [23]:
arr=np.array([[[1,2,3],[3,4,5],[7,8,9]]])
print(arr)
print(arr.ndim)
print("shape",arr.shape)

[[[1 2 3]
  [3 4 5]
  [7 8 9]]]
3
shape (1, 3, 3)


In [ ]:
# Assignment
4-D array , 5-D array and 6D-array

# Built in function to generate numpy array

In [ ]:
# arange : It is used to generate evenly spaced values within a given interval
Note: end value is not included

In [25]:
# generate values from 0 to 14
np.arange(15)   # end value is not included

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
# generate values from 0 to 30
np.arange(31)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [28]:
# generate values from 101 to 150
# arange(start,end)
np.arange(101,151)


array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [29]:
# generate values from 400 to 480
np.arange(400,481)

array([400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
       413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
       426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438,
       439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
       452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
       465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
       478, 479, 480])

In [32]:
# generate first 10 even even number
# arange(start,end,step)
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
# generate an array which includes 10 multiples of 5
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [35]:
# can u find 10 multiples of 8
np.arange(8,81,8)

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

# ones


In [ ]:
# ones: returns an array with all one

In [36]:
# return 1-D array with 3 elements as 1
np.ones(3) 

array([1., 1., 1.])

In [37]:
# return 1-D arry 10 elements as 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
# create unit matrix of order (2,2)
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [39]:
# create unit matrix of order (5,3)
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# zeros

In [40]:
# create an 1-D array with  5 elements as 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
# create 2_d array or order (3,3)
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# eye-- Identity

In [42]:
# create (2,2) identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [44]:
# create (3,3) identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
# create (4,3) identity matrix
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

# full-- It is used generate array with same elements

In [48]:
# craete (2,2) with all elements as 10
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [49]:
# create (4,3) matrix with all elements as 20
np.full((4,3),20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

# linspace--It is used to generate linearly spaced values

In [61]:
# generate linearly spaced values between 1 to 5
np.linspace(1,100,retstep=True)

(array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
         25.24489796,  27.26530612,  29.28571429,  31.30612245,
         33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
         41.40816327,  43.42857143,  45.44897959,  47.46938776,
         49.48979592,  51.51020408,  53.53061224,  55.55102041,
         57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
         65.65306122,  67.67346939,  69.69387755,  71.71428571,
         73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
         81.81632653,  83.83673469,  85.85714286,  87.87755102,
         89.89795918,  91.91836735,  93.93877551,  95.95918367,
         97.97959184, 100.        ]),
 2.020408163265306)

In [56]:
np.arange(1,5,0.067)

array([1.   , 1.067, 1.134, 1.201, 1.268, 1.335, 1.402, 1.469, 1.536,
       1.603, 1.67 , 1.737, 1.804, 1.871, 1.938, 2.005, 2.072, 2.139,
       2.206, 2.273, 2.34 , 2.407, 2.474, 2.541, 2.608, 2.675, 2.742,
       2.809, 2.876, 2.943, 3.01 , 3.077, 3.144, 3.211, 3.278, 3.345,
       3.412, 3.479, 3.546, 3.613, 3.68 , 3.747, 3.814, 3.881, 3.948,
       4.015, 4.082, 4.149, 4.216, 4.283, 4.35 , 4.417, 4.484, 4.551,
       4.618, 4.685, 4.752, 4.819, 4.886, 4.953, 5.02 , 5.087, 5.154,
       5.221, 5.288, 5.355, 5.422, 5.489, 5.556, 5.623, 5.69 , 5.757,
       5.824, 5.891, 5.958])

In [52]:
# generate 10 equally spaced values between 1 to 100
np.linspace(1,100,num=10,retstep=True)

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [53]:
# generate 10 numbers between 1 to 1000 and find the difference
np.linspace(1,1000,num=10,retstep=True)

(array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
        1000.]),
 111.0)

# Random

# randint

In [4]:
# create an array which includes 10 random integers between 1 to 100
# randint-- it is used to generate random integers for given interval
np.random.randint(1,100,10)

array([11, 67, 46, 12, 41, 94, 64, 82, 60, 96])

In [5]:
# generate an array which includes 5 random integers between 1 to 1000
np.random.randint(1,1000,5)

array([125, 390, 651, 320, 460])

In [6]:
# create 2-d array of order (2,2) which includes random integers between 20 to 60
np.random.randint(20,60,size=(2,2))

array([[36, 43],
       [33, 26]])

In [7]:
# create 2-d array of order (2,3) which includes random integers between 2 to 200
np.random.randint(2,200,size=(2,3))

array([[159,  89, 151],
       [122,  21,  14]])

# rand

In [ ]:
# rand--It generates random values between the range [0,1]

In [8]:
# generate 10 random numbers between o to 1
np.random.rand(10)

array([0.28015128, 0.48067812, 0.921967  , 0.58221325, 0.81161653,
       0.79799759, 0.64646573, 0.34290723, 0.04393684, 0.71790712])

In [9]:
# generate 100 random numbers between o to 1
np.random.rand(100)

array([0.14456829, 0.10080537, 0.14012401, 0.48888084, 0.00293531,
       0.9236439 , 0.98758701, 0.067925  , 0.31239859, 0.79894734,
       0.94548306, 0.65468341, 0.90450694, 0.5938654 , 0.82793226,
       0.66728375, 0.70399752, 0.05710403, 0.26425229, 0.21873957,
       0.01894274, 0.17518527, 0.87574159, 0.38660241, 0.57651154,
       0.99171056, 0.58541776, 0.13441813, 0.77704185, 0.08741209,
       0.23371118, 0.87569253, 0.76338965, 0.54487671, 0.36410817,
       0.5630557 , 0.12681828, 0.68361077, 0.49704309, 0.68219828,
       0.64365612, 0.59806309, 0.78591249, 0.77667315, 0.23677448,
       0.73463379, 0.73189972, 0.14418762, 0.0140613 , 0.99038958,
       0.426432  , 0.96694686, 0.49445104, 0.22483084, 0.06721021,
       0.28499187, 0.47281351, 0.20527407, 0.29591912, 0.32654593,
       0.92136457, 0.65324342, 0.14177154, 0.00415048, 0.17353637,
       0.21821251, 0.81755254, 0.10323693, 0.15381051, 0.52366461,
       0.82802799, 0.61055791, 0.97698003, 0.97122206, 0.87985

In [10]:
# create 2d array of order (4,4) with random numbers between 0 to 1
np.random.rand(4,4)

array([[0.76483669, 0.48254754, 0.52686204, 0.5118798 ],
       [0.85005364, 0.4460909 , 0.53289565, 0.01705954],
       [0.28973515, 0.03033238, 0.68187256, 0.1042449 ],
       [0.17761618, 0.53482353, 0.46332209, 0.47691376]])

In [11]:
# create matrix of order (7,3) which includes numbers between 0 to 1
np.random.rand(7,3)

array([[0.38847877, 0.7047607 , 0.50156033],
       [0.22698585, 0.27619918, 0.28273905],
       [0.18576572, 0.46938297, 0.82798059],
       [0.76124966, 0.99108748, 0.76257414],
       [0.81919723, 0.65836817, 0.18851446],
       [0.454941  , 0.44807531, 0.51968621],
       [0.59094733, 0.03824574, 0.94879893]])

# randn

In [ ]:
 #It is used to generate random numbers from normal distribution within a range [-3,3]

In [18]:
# generate 10 random numbers from normal distribution
np.random.randn(10)

array([-0.30656252, -0.32009882, -1.39538498, -2.61744579, -0.33397405,
       -1.22323787,  0.02485403,  0.30809748,  0.86124016,  0.05192984])

In [ ]:
## create 2d array of order (5,5) which includes normal distribution values

In [19]:
np.random.randn(5,5)

array([[-0.72514462, -0.95284986,  0.18359432,  0.03146468, -0.89486939],
       [ 0.19807413,  0.33650793, -0.53568307,  1.17429583,  0.94214528],
       [ 0.34282016,  0.37515666,  1.19295271, -0.24663459,  1.78962249],
       [ 0.55879473, -1.95920742,  0.96968103, -1.59502067, -0.03051984],
       [-1.39791949, -0.88752701,  0.85183476,  0.84998693,  1.01043423]])

In [21]:
# create 10 random integers between 1 to 10000
arr=np.random.randint(1,10000,10)
print(arr)

[3806 8954 6375 7060 3801 2566 5551 3787 6506 1939]


In [22]:
# maximum value
np.max(arr)

8954

In [23]:
# argmax- It is used to get the index value of maximum value in an array
np.argmax(arr)

1

In [24]:
# minimum
np.min(arr)

1939

In [25]:
# index position of minimum value
np.argmin(arr)

9

# Indexing

In [28]:
A=np.arange(20,30)
print(A)

[20 21 22 23 24 25 26 27 28 29]


In [29]:
# fetch 23
A[3]

23

In [30]:
# fetch 23,24,25
A[3:6]

array([23, 24, 25])

In [31]:
A[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

## Indexing with 2-D array

In [32]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# fetch first row
arr[[0]]

array([[1, 2, 3]])

In [35]:
# fetch third row
arr[[2]]

array([[7, 8, 9]])

In [38]:
## fetch first and second row
arr[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
## fetch first and third row
arr[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [40]:
# fetch 4
arr[1][0]

4

In [41]:
# fetch 9
arr[2][2]

9

In [42]:
# fetch 6
arr[1,2]

6

In [44]:
# fetch first column
arr[:,[0]]

array([[1],
       [4],
       [7]])

In [46]:
# fetch third column
arr[:,[2]]

array([[3],
       [6],
       [9]])

In [47]:
# fetch 1st and 3rd column
arr[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [48]:
# fetch 1st and second column
arr[:,[0,1]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [49]:
arr1=np.array([10,20,30,40,50])
arr2=np.array([2,4,6,8,10])

In [50]:
arr1+arr2

array([12, 24, 36, 48, 60])

In [51]:
arr1-arr2

array([ 8, 16, 24, 32, 40])

In [52]:
arr1*arr2

array([ 20,  80, 180, 320, 500])

In [53]:
arr1/arr2

array([5., 5., 5., 5., 5.])

In [54]:
arr1+5

array([15, 25, 35, 45, 55])

In [58]:
arr1-30

array([-20, -10,   0,  10,  20])

In [ ]:
# Assignment

In [ ]:
arr1=np.array()